[package]
name = "cofd-meta"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cofd-schema.workspace = true
regex.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_regex = "1"
