[alias]
meta-edit = [
	"run",
	"-p",
	"meta-editor",
	"--",
]

#[target.x86_64-unknown-linux-gnu]
#linker = "clang"
#rustflags = ["/home/m00n/Documents/Projects/Rust-C", "link-arg=-fuse-ld=/usr/bin/mold"]